import type { Err, Ok, Result } from "./result";
import { err, ok } from "./result";
import { SafeFnBuilder } from "./safe-fn";

import type {
  AnyCompleteSafeFn,
  AnyRunnableSafeFn,
  AnySafeFn,
  AnySafeFnThrownHandler,
  BuilderSteps,
  InferCompleteFnReturn,
  InferCompleteFnReturnData,
  InferCompleteFnReturnError,
  InferCompleteFnRunArgs,
  InferInputSchema,
  InferOutputSchema,
  InferReturn,
  InferReturnData,
  InferReturnError,
  InferRunArgs,
  InferUnparsedInput,
  SafeFnActionFn,
  SafeFnReturn,
  SafeFnReturnData,
  SafeFnReturnError,
  SafeFnRunArgs,
  TSafeFn,
} from "./types";

export { err, ok, SafeFnBuilder as SafeFn };
export type {
  AnyCompleteSafeFn,
  AnyRunnableSafeFn,
  AnySafeFn,
  AnySafeFnThrownHandler,
  BuilderSteps,
  Err,
  InferCompleteFnReturn,
  InferCompleteFnReturnData,
  InferCompleteFnReturnError,
  InferCompleteFnRunArgs,
  InferInputSchema,
  InferOutputSchema,
  InferReturn,
  InferReturnData,
  InferReturnError,
  InferRunArgs,
  InferUnparsedInput,
  Ok,
  Result,
  SafeFnActionFn,
  SafeFnReturn,
  SafeFnReturnData,
  SafeFnReturnError,
  SafeFnRunArgs,
  TSafeFn,
};
