import type { Err, Ok, Result } from "./result";
import {
  actionResultToResult,
  err,
  ok,
  type ActionErr,
  type ActionOk,
  type ActionResult,
  type ActionResultToResult,
  type InferActionErrError,
  type InferActionOkData,
} from "./result";
import { SafeFnBuilder } from "./safe-fn-builder";

import type {
  AnyRunnableSafeFn,
  AnySafeFnAction,
  AnySafeFnThrownHandler,
  InferInputSchema,
  InferOutputSchema,
  InferSafeFnActionArgs,
  InferSafeFnActionError,
  InferSafeFnActionOkData,
  InferSafeFnActionReturn,
  InferSafeFnArgs,
  InferSafeFnErrError,
  InferSafeFnOkData,
  InferSafeFnReturn,
  InferUnparsedInput,
  SafeFnAction,
  SafeFnActionArgs,
  SafeFnActionReturn,
  SafeFnAsyncGeneratorHandlerFn,
  SafeFnRegularHandlerFn,
  SafeFnReturn,
  SafeFnReturnData,
  SafeFnReturnError,
  SafeFnRunArgs,
} from "./types";

export { actionResultToResult, err, ok, SafeFnBuilder as SafeFn };
export type {
  ActionErr,
  ActionOk,
  ActionResult,
  ActionResultToResult,
  AnyRunnableSafeFn,
  AnySafeFnAction,
  AnySafeFnThrownHandler,
  Err,
  InferActionErrError,
  InferActionOkData,
  InferInputSchema,
  InferOutputSchema,
  InferSafeFnActionArgs,
  InferSafeFnActionError,
  InferSafeFnActionOkData,
  InferSafeFnActionReturn,
  InferSafeFnArgs,
  InferSafeFnErrError,
  InferSafeFnOkData,
  InferSafeFnReturn,
  InferUnparsedInput,
  Ok,
  Result,
  SafeFnAction,
  SafeFnActionArgs,
  SafeFnActionReturn,
  SafeFnAsyncGeneratorHandlerFn,
  SafeFnRegularHandlerFn,
  SafeFnReturn,
  SafeFnReturnData,
  SafeFnReturnError,
  SafeFnRunArgs,
};
