import type { Err, Ok, Result } from "./result";
import { err, ok } from "./result";
import { SafeFnBuilder } from "./safe-fn-builder";

import type {
  AnyRunnableSafeFn,
  AnySafeFnAction,
  AnySafeFnThrownHandler,
  InferInputSchema,
  InferOutputSchema,
  InferReturn,
  InferReturnData,
  InferReturnError,
  InferRunArgs,
  InferSafeFnActionArgs,
  InferSafeFnActionError,
  InferSafeFnActionOkData,
  InferSafeFnActionReturn,
  InferUnparsedInput,
  SafeFnAction,
  SafeFnActionArgs,
  SafeFnActionReturn,
  SafeFnHandlerFn,
  SafeFnReturn,
  SafeFnReturnData,
  SafeFnReturnError,
  SafeFnRunArgs,
} from "./types";

export { err, ok, SafeFnBuilder as SafeFn };
export type {
  AnyRunnableSafeFn,
  AnySafeFnAction,
  AnySafeFnThrownHandler,
  Err as Err,
  InferInputSchema,
  InferOutputSchema,
  InferReturn,
  InferReturnData,
  InferReturnError,
  InferRunArgs,
  InferSafeFnActionArgs,
  InferSafeFnActionError,
  InferSafeFnActionOkData,
  InferSafeFnActionReturn,
  InferUnparsedInput,
  Ok,
  Result,
  SafeFnAction,
  SafeFnActionArgs,
  SafeFnActionReturn,
  SafeFnHandlerFn,
  SafeFnReturn,
  SafeFnReturnData,
  SafeFnReturnError,
  SafeFnRunArgs,
};
