# Adopted from https://github.com/changesets/action
name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

# TODO: optimize caching
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: "Setup PNPM"
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --filter "\!./apps/**" --frozen-lockfile
      - name: "Build packages"
        run: pnpm build-packages
      - name: "Run type-check"
        run: pnpm check-types
      - name: "Run lint"
        run: pnpm lint
      - name: "Run tests"
        run: pnpm test

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
